imports:
    - { resource: services/api.yml }
    - { resource: services/authenticators.yml }
    - { resource: services/client.yml }
    - { resource: services/commands.yml }
    - { resource: services/controllers.yml }
    - { resource: services/converters.yml }
    - { resource: services/credentials_checker.yml }
    - { resource: services/events.yml }
    - { resource: services/exporter.yml }
    - { resource: services/factory.yml }
    - { resource: services/fields.yml }
    - { resource: services/file.yaml }
    - { resource: services/generators.yml }
    - { resource: services/helpers.yml }
    - { resource: services/mappers.yml }
    - { resource: services/response.yml }
    - { resource: services/services.yml }
    - { resource: services/twig.yml }
    - { resource: services/values.yml }
